/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.

## What is this?

This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

We've covered everything from Pokémon to Berry Flavors.

## Where do I start?

We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.

This API will always be publicly available and will never require any extensive setup process to consume.

Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
    
 * OpenAPI spec version: 2.7.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  LanguageDetail,
  LanguageListParams,
  PaginatedLanguageSummaryList
} from '.././model';





/**
 * Languages for translations of API resource information.
 * @summary List languages
 */
export type languageListResponse200 = {
  data: PaginatedLanguageSummaryList
  status: 200
}
    
export type languageListResponseComposite = languageListResponse200;
    
export type languageListResponse = languageListResponseComposite & {
  headers: Headers;
}

export const getLanguageListUrl = (params?: LanguageListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://pokeapi.co/api/v2/language/?${stringifiedParams}` : `https://pokeapi.co/api/v2/language/`
}

export const languageList = async (params?: LanguageListParams, options?: RequestInit): Promise<languageListResponse> => {
  
  const res = await fetch(getLanguageListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: languageListResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as languageListResponse
}



export const getLanguageListQueryKey = (params?: LanguageListParams,) => {
    return [`https://pokeapi.co/api/v2/language/`, ...(params ? [params]: [])] as const;
    }

    
export const getLanguageListQueryOptions = <TData = Awaited<ReturnType<typeof languageList>>, TError = unknown>(params?: LanguageListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLanguageListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof languageList>>> = ({ signal }) => languageList(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof languageList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LanguageListQueryResult = NonNullable<Awaited<ReturnType<typeof languageList>>>
export type LanguageListQueryError = unknown


export function useLanguageList<TData = Awaited<ReturnType<typeof languageList>>, TError = unknown>(
 params: undefined |  LanguageListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof languageList>>,
          TError,
          Awaited<ReturnType<typeof languageList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLanguageList<TData = Awaited<ReturnType<typeof languageList>>, TError = unknown>(
 params?: LanguageListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof languageList>>,
          TError,
          Awaited<ReturnType<typeof languageList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLanguageList<TData = Awaited<ReturnType<typeof languageList>>, TError = unknown>(
 params?: LanguageListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List languages
 */

export function useLanguageList<TData = Awaited<ReturnType<typeof languageList>>, TError = unknown>(
 params?: LanguageListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLanguageListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Languages for translations of API resource information.
 * @summary Get language
 */
export type languageRetrieveResponse200 = {
  data: LanguageDetail
  status: 200
}
    
export type languageRetrieveResponseComposite = languageRetrieveResponse200;
    
export type languageRetrieveResponse = languageRetrieveResponseComposite & {
  headers: Headers;
}

export const getLanguageRetrieveUrl = (id: string,) => {


  

  return `https://pokeapi.co/api/v2/language/${id}/`
}

export const languageRetrieve = async (id: string, options?: RequestInit): Promise<languageRetrieveResponse> => {
  
  const res = await fetch(getLanguageRetrieveUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: languageRetrieveResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as languageRetrieveResponse
}



export const getLanguageRetrieveQueryKey = (id: string,) => {
    return [`https://pokeapi.co/api/v2/language/${id}/`] as const;
    }

    
export const getLanguageRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof languageRetrieve>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageRetrieve>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLanguageRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof languageRetrieve>>> = ({ signal }) => languageRetrieve(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof languageRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LanguageRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof languageRetrieve>>>
export type LanguageRetrieveQueryError = unknown


export function useLanguageRetrieve<TData = Awaited<ReturnType<typeof languageRetrieve>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof languageRetrieve>>,
          TError,
          Awaited<ReturnType<typeof languageRetrieve>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLanguageRetrieve<TData = Awaited<ReturnType<typeof languageRetrieve>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof languageRetrieve>>,
          TError,
          Awaited<ReturnType<typeof languageRetrieve>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLanguageRetrieve<TData = Awaited<ReturnType<typeof languageRetrieve>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageRetrieve>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get language
 */

export function useLanguageRetrieve<TData = Awaited<ReturnType<typeof languageRetrieve>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof languageRetrieve>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLanguageRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



